### ISSUE TITLE
Error during start

### ISSUE THREAD

**Issue by Goki92** [AlexRubik/rude-bot-solana#1]
Hello,
I'm trying your bot, in the meantime thank you very much for the work done.

I checked the documentation, but I haven't found anywhere the explanation of what the parameter "PAYER_KEYPAIR_PATH=/full/path/to/payer/keypair.json" is.
When I try to start the bot I have the following error:

`Error: ENOENT: no such file or directory, open '/full/path/to/payer/keypair.json'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Object.openSync (node:fs:585:3)
    at Object.openSync (pkg/prelude/bootstrap.js:793:32)
    at Object.readFileSync (node:fs:453:35)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1079:36)
    at Object.<anonymous> (/snapshot/rude-bot/dist/executeOneQuote.js)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/full/path/to/payer/keypair.json',
  pkg: true
`
Can you please explain me what I have to set to this parameter?

Thank you so much.

**Comment by Goki92** [comment]
Hello,
I found the solution, I created a keypair with solana tools.
Thank you.

**Comment by AlexRubik** [comment]
Will update the docs for this at some point but the bot requires a json keypair that you can create with the Solana CLI.
https://solana.com/developers/guides/getstarted/setup-local-development#3-install-the-solana-cli

This link shows you how to install the CLI and if you scroll down, it gives you the commands to create a new keypair (wallet) json as well.
