### ISSUE TITLE
running the bot

### ISSUE THREAD

**Issue by reign420** [AlexRubik/rude-bot-solana#4]
running into this error currently when trying to run the file on the vps any help would be great 
root@racknerd-0b2724e:~/rude-bot-alpha0_2_7# ./rude-bot-alpha0_2_7
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
No HTTP or HTTPS prefix found in BLOCK_ENGINE_URL; defaulting to HTTPS.
Uncaught Exception thrown: SyntaxError: Unexpected token , in JSON at position 268
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/snapshot/rude-bot/dist/src/execute.js)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/rude-bot/dist/src/arb.js)
Uncaught Exception thrown: SyntaxError: Unexpected token , in JSON at position 268
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/snapshot/rude-bot/dist/src/execute.js)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/rude-bot/dist/src/arb.js)

**Comment by AlexRubik** [comment]
Hey! @reign420 , looks like you have a syntax error in one of the json files you modified. You can post the incorrect json (maybe it was baseConfig.json?) or put it in chatgpt or claude and it will tell you where the syntax error is.

And the quickest way to get help is by posting in the support channel of our Discord: https://discord.gg/6DTGbMNYuA

Thanks!

**Comment by reign420** [comment]
just now figgured it out, thanks for pointing me in the right direction!
